#!/usr/bin/env python3
"""Rebuild README.md from profile.yml — profile.yml is the single source of truth."""
from pathlib import Path
from urllib.parse import quote

import yaml

ROOT = Path(__file__).resolve().parents[1]
cfg = yaml.safe_load((ROOT / "profile.yml").read_text(encoding="utf-8"))

user = cfg["username"]
header = cfg.get("header") or {}
stats_cfg = cfg.get("stats") or {}
social = cfg.get("social") or {}

title = header.get("title") or f"Hi, I'm {user}"
subtitle = (header.get("subtitle") or "").strip()
colors = header.get("colors") or "0:6a11cb,50:8e2de2,100:2575fc"
theme = stats_cfg.get("theme") or "tokyonight"


def enc(s: str) -> str:
    """URL-encode a query value, keeping it safe for & and ; separators."""
    return quote(str(s), safe="")


def badge(label: str, color: str, logo: str | None = None, logo_color: str = "white") -> str:
    text = quote(str(label).replace("-", "--").replace(" ", "_"))
    extra = f"&logo={logo}&logoColor={logo_color}" if logo else ""
    return f"https://img.shields.io/badge/{text}-{str(color).lstrip('#')}?style=flat-square{extra}"


def img(src: str, alt: str, extra: str = "") -> str:
    return f'<img src="{src}" alt="{alt}"{extra} />'


sections: list[str] = []
sections.append(
    "<!-- ⚠️ AUTO-GENERATED from profile.yml — do not edit this file by hand.\n"
    "     Edit profile.yml (repo root), push, and Actions rebuilds this page.\n"
    "     本页面由 profile.yml 自动生成：请修改 profile.yml，不要直接改本文件。 -->"
)

# ---- header banner ----
capsule = (
    f"https://capsule-render.vercel.app/api?type=waving&color={colors}"
    f"&height=200&section=header&text={enc(title)}&fontSize=52&fontColor=ffffff&fontAlignY=36"
)
if subtitle:
    capsule += f"&desc={enc(subtitle)}&descSize=17&descAlignY=62"
capsule += "&animation=fadeIn"
sections.append('<p align="center">\n  ' + img(capsule, "header", ' width="100%"') + "\n</p>")

# ---- typing animation ----
lines = [l for l in (cfg.get("typing") or []) if str(l).strip()]
if lines:
    src = (
        "https://readme-typing-svg.demolab.com?font=JetBrains+Mono&weight=600&size=22"
        "&duration=3500&pause=1000&color=6C9BFF&center=true&vCenter=true&width=720&height=70"
        f"&lines={';'.join(enc(l) for l in lines)}"
    )
    sections.append(
        f'<p align="center">\n  <a href="https://github.com/{user}">\n'
        f"    {img(src, 'Typing SVG')}\n  </a>\n</p>"
    )

# ---- visitors badge ----
if stats_cfg.get("show_visitors", True):
    sections.append(
        '<p align="center">\n  '
        + img(
            f"https://api.visitorbadge.io/api/VisitorHit?user={user}&repo={user}&type=ip",
            "profile views",
        )
        + "\n</p>"
    )

sections.append("---")

# ---- about ----
about = [l for l in (cfg.get("about") or []) if str(l).strip()]
if about:
    body = "\n".join(f"- {l}" for l in about)
    sections.append(f"## 🧭 About Me\n\n{body}")

# ---- tech stack ----
icons = [i for i in (cfg.get("skills_icons") or []) if str(i).strip()]
groups = cfg.get("badge_groups") or []
stack: list[str] = []
if icons:
    icons_param = ",".join(icons)
    stack.append(
        '<p align="center">\n  '
        f'<a href="https://github.com/{user}?tab=repositories">\n'
        f"    {img(f'https://skillicons.dev/icons?i={icons_param}', 'skills')}\n  </a>\n</p>"
    )
for g in groups:
    badges = g.get("badges") or []
    if not badges:
        continue
    row = "\n  ".join(
        img(badge(b["label"], b.get("color", "36BCF7"), b.get("logo"), b.get("logo_color", "white")), b["label"])
        for b in badges
    )
    stack.append(f'<p align="center">\n  <strong>{g.get("title", "")}</strong><br/>\n  {row}\n</p>')
if stack:
    sections.append("## 🛠️ Tech Stack\n\n" + "\n\n".join(stack))

# ---- hobbies ----
hobbies = cfg.get("hobbies") or []
if hobbies:
    row = "\n  ".join(
        img(badge(h["label"], h.get("color", "36BCF7")), h["label"]) for h in hobbies
    )
    sections.append(f'## 🏀 Hobbies & Interests\n\n<p align="center">\n  {row}\n</p>')

# ---- social links ----
social_items: list[tuple[str, str, str, str | None]] = []
if social.get("email"):
    social_items.append((f"mailto:{social['email']}", "Email", "0078D4", None))
if social.get("blog"):
    social_items.append((social["blog"], "Website", "000000", "googlechrome"))
if social.get("twitter"):
    social_items.append((f"https://x.com/{social['twitter']}", "X / Twitter", "000000", "x"))
if social.get("linkedin"):
    social_items.append(
        (f"https://www.linkedin.com/in/{social['linkedin']}", "LinkedIn", "0A66C2", None)
    )
if social.get("bilibili"):
    social_items.append(
        (f"https://space.bilibili.com/{social['bilibili']}", "Bilibili", "FB7299", "bilibili")
    )
if social.get("zhihu"):
    social_items.append(
        (f"https://www.zhihu.com/people/{social['zhihu']}", "Zhihu", "0084FF", "zhihu")
    )
if social_items:
    row = "\n  ".join(
        f'<a href="{href}">{img(badge(label, color, logo), label)}</a>'
        for href, label, color, logo in social_items
    )
    sections.append(
        "## 🤝 Connect with Me\n\n<p align=\"center\">\n  " + row + "\n</p>"
    )

# ---- stats ----
show_stats = stats_cfg.get("show_streak", True) or True  # main cards always shown
stat_card = img(
    f"https://github-readme-stats.vercel.app/api?username={user}&show_icons=true&theme={theme}&hide_border=true",
    "GitHub stats",
    ' height="165"',
)
langs_card = img(
    f"https://github-readme-stats.vercel.app/api/top-langs/?username={user}&layout=compact&theme={theme}&hide_border=true&langs_count=8",
    "Top languages",
    ' height="165"',
)
stats_blocks = [
    f'<p align="center">\n  <table>\n    <tr>\n'
    f"      <td align=\"center\">\n        {stat_card}\n      </td>\n"
    f"      <td align=\"center\">\n        {langs_card}\n      </td>\n    </tr>\n  </table>\n</p>"
]
if stats_cfg.get("show_streak", True):
    stats_blocks.append(
        '<p align="center">\n  '
        + img(
            f"https://streak-stats.demolab.com?user={user}&theme={theme}&hide_border=true",
            "GitHub streak",
            ' height="165"',
        )
        + "\n</p>"
    )
if stats_cfg.get("show_trophy", False):
    stats_blocks.append(
        '<p align="center">\n  '
        + img(
            f"https://github-profile-trophy.vercel.app/?username={user}&theme={theme}&no-frame=true&row=1&column=7",
            "Trophies",
            ' width="100%"',
        )
        + "\n</p>"
    )
sections.append("## 📊 GitHub Stats\n\n" + "\n\n".join(stats_blocks))

# ---- snake ----
if stats_cfg.get("show_snake", True):
    base = f"https://raw.githubusercontent.com/{user}/{user}/output"
    sections.append(
        "## 🐍 Contribution Snake\n\n<p align=\"center\">\n  <picture>\n"
        f'    <source media="(prefers-color-scheme: dark)" srcset="{base}/github-contribution-grid-snake-dark.svg" />\n'
        f'    <source media="(prefers-color-scheme: light)" srcset="{base}/github-contribution-grid-snake.svg" />\n'
        f'    <img alt="contribution snake animation" src="{base}/github-contribution-grid-snake.svg" width="100%" />\n'
        "  </picture>\n</p>"
    )

# ---- footer ----
sections.append("---")
sections.append(
    '<p align="center">\n  '
    + img(
        f"https://capsule-render.vercel.app/api?type=waving&color={colors}&height=110&section=footer",
        "footer",
        ' width="100%"',
    )
    + "\n</p>"
)

out = "\n\n".join(sections) + "\n"
readme = ROOT / "README.md"
if readme.exists() and readme.read_text(encoding="utf-8") == out:
    print("README.md already up to date")
else:
    readme.write_text(out, encoding="utf-8", newline="\n")
    print("README.md rebuilt from profile.yml")
